# Generated by Django 4.2.25 on 2025-11-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affacturage',
            name='SIGLE_I01',
            field=models.CharField(max_length=30, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='cautions',
            name='SIGLE_I01',
            field=models.CharField(max_length=30, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='decouverts',
            name='SIGLE_I01',
            field=models.CharField(max_length=30, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='effets_commerces',
            name='SIGLE_I01',
            field=models.CharField(max_length=30, verbose_name='Sigle'),
        ),
    ]
