# Generated by Django 4.2.25 on 2025-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnef', '0002_alter_affacturage_sigle_i01_alter_cautions_sigle_i01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautions',
            name='BENEFICAIRE_I06',
            field=models.CharField(max_length=125, verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='decouverts',
            name='BENEFICAIRE_I04',
            field=models.CharField(max_length=125, verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='effets_commerces',
            name='BENEFICAIRE_I06',
            field=models.CharField(max_length=125, verbose_name='Bénéficiaire'),
        ),
    ]
