# Generated by Django 4.2.25 on 2025-11-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnef', '0003_alter_cautions_beneficaire_i06_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_amortissables',
            name='BENEFICIAIRE_I06',
            field=models.CharField(max_length=125, verbose_name='Bénéficiaire'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='BENEFICIAIRE_I06',
            field=models.CharField(max_length=125, verbose_name='Bénéficiaire'),
        ),
    ]
