# Generated by Django 4.2.25 on 2025-11-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnef', '0004_alter_credit_amortissables_beneficiaire_i06_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(choices=[('INVITATION', 'Invitation'), ('VALIDATION', 'Validation de fichier'), ('REJET', 'Rejet de fichier'), ('NOTIFICATION_ACNEF', 'Notification ACNEF')], max_length=50, verbose_name="Type d'email")),
                ('destinataire_email', models.EmailField(max_length=255, verbose_name='Email du destinataire')),
                ('destinataire_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du destinataire')),
                ('objet', models.CharField(max_length=255, verbose_name="Objet de l'email")),
                ('contenu_html', models.TextField(verbose_name="Contenu HTML de l'email")),
                ('contenu_texte', models.TextField(blank=True, null=True, verbose_name='Contenu texte (fallback)')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé avec succès'), ('ECHEC', "Échec d'envoi")], default='ENVOYE', max_length=20, verbose_name="Statut d'envoi")),
                ('erreur_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur (si échec)")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_lies', to='cnef.etablissement', verbose_name='Établissement concerné')),
                ('fichier_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='cnef.fichierimport', verbose_name='Fichier lié')),
                ('token_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='cnef.tokeninscription', verbose_name="Token d'inscription lié")),
                ('utilisateur_envoyeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Historique Email',
                'verbose_name_plural': 'Historique Emails',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['-date_envoi'], name='cnef_histor_date_en_bcf06d_idx'), models.Index(fields=['type_email'], name='cnef_histor_type_em_5fe4ea_idx'), models.Index(fields=['statut'], name='cnef_histor_statut_3b5b54_idx'), models.Index(fields=['destinataire_email'], name='cnef_histor_destina_d07471_idx')],
            },
        ),
    ]
