# Generated by Django 4.2.27 on 2025-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnef", "0005_historiqueemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionutilisateur",
            name="type_action",
            field=models.CharField(
                choices=[
                    ("CONNEXION", "Connexion"),
                    ("DECONNEXION", "Déconnexion"),
                    ("UPLOAD_FICHIER", "Upload de fichier"),
                    ("VALIDATION_FICHIER", "Validation de fichier"),
                    ("REJET_FICHIER", "Rejet de fichier"),
                    (
                        "TELECHARGEMENT_FICHIER_ORIGINAL",
                        "Téléchargement de fichier original",
                    ),
                    ("CREATION_UTILISATEUR", "Création d'utilisateur"),
                    ("MODIFICATION_UTILISATEUR", "Modification d'utilisateur"),
                    ("SUPPRESSION_FICHIER", "Suppression de fichier"),
                    ("SUPPRESSION_ETABLISSEMENT", "Suppression d'établissement"),
                    ("CREATION_ETABLISSEMENT", "Création d'établissement"),
                    ("MODIFICATION_ETABLISSEMENT", "Modification d'établissement"),
                    ("GENERER_COMMUNIQUE_PRESSE", "Génération du communiqué de presse"),
                    ("GENERATION_LIEN", "Génération de lien d'inscription"),
                    ("UTILISATION_TOKEN", "Utilisation d'un token d'inscription"),
                    (
                        "REINITIALISATION_MOT_DE_PASSE",
                        "Réinitialisation de mot de passe",
                    ),
                    ("RENVOI_EMAIL", "Renvoi email de validation"),
                    ("AUTRE", "Autre action"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="categorie_emf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PREMIERE_CATEGORIE", "1re Catégorie"),
                    ("DEUXIEME_CATEGORIE", "2e Catégorie"),
                    ("TROISIEME_CATEGORIE", "3e Catégorie"),
                ],
                max_length=20,
                null=True,
                verbose_name="Catégorie EMF",
            ),
        ),
    ]
